version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    groups:
      nuget-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    groups:
      docker-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
