<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\TutoringCentre.Application\TutoringCentre.Application.csproj" />
    <ProjectReference Include="..\TutoringCentre.Domain\TutoringCentre.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>
</Project>
